### PR TITLE
Restructure IoK with Redux

### LINKED ISSUE #64: Make nodes delete-able
Currently, to delete a node, one must delete the whole graph and then reconstruct it, minus that one node. This is O(n) time complexity for humans. A bit much. We could reduce it.

### LINKED ISSUE #82: [v4] add redux

### LINKED ISSUE #88: Toolbar
Make a toolbar for the lefthand side of the IoK Website

Proposed features would include 
1. selecting, adding, editing, deleting, merging nodes
2. importing another IoK, see #75 
3. publishing and downloading the IoK 

Screen Shot 2020-06-15 at 10 04 29 AM

### PR DESCRIPTION
**Pull request by susan-lin**
## Motivation

Following the previous PR, we finished adding in redux. We wanted to update the user interface (setting up the toolbar and sidebar) of the Index of Knowledge as well. 

## Test Plan

The new toolbar should work as intended; we have also updated our test for the graph reducer.

## Related PRs or Issues
Resolves #64 
Resolves #82 
Resolves #88

### CODE REVIEW

**Comment by rustielin** [comment]
Is the build on your staging environment 9https://iok-susan.web.app/) up to date?

**Comment by susan-lin** [comment]
Ah! Yes it should be -- but in regards to your slack message, I think we commented that out in App.jsx for this PR (will need to fix that).

**Comment by rustielin** [comment]
> I think we commented that out in App.jsx

Can you fix that in this PR? otherwise beta and prod builds will be in a bad state @susan-lin

**Comment by rustielin** [comment]
Some general comments playing with your hosted version:
* Graph layout is a bit confusing when adding nodes. "recenter graph" option would be nice
* Input validation for add/edit nodes is missing
* Deleting root node deletes all children. This makes sense for resources nodes but not really for topic nodes.
* Storage missing, as noted in above comment ^, and also graph upload (ipfs) is broken

**Comment by susan-lin** [comment]
@rustielin 
Yes, will do!

**Comment by rustielin** [comment]
Let me know when this is ready for review & your firebase staging envs have been updated

**Comment by rianadon** [comment]
We're ready! You can view our staging at [https://iok-susan.web.app](https://iok-ryan.web.app)! There are a few easter eggs :egg:

**Pull request merged**
